### ISSUE TITLE
[Draft] DCR: Check API compatibility changes as part of the build process

### ISSUE THREAD

**Issue by Aliandi** [southworks/botbuilder-dotnet#36]
Currently, there's no check to validate API compatibility with latest version of the SDK upon changes in the code.

## Requirement
We want to detect when there are changes and/or incompatibilities between the currently published SDK API and the one being built from the repository.

## Proposal
We propose using the [ApiCompat](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat) tool, which compares one or more binaries against another set of binaries to check them for compatibility issues. If one or more issues are found, _ApiCompat_ will output the incompatibilities found.
In order to implement it without adding extra steps to the users, the best option is to add this tool as a Pipeline Task in the build server.
  
### ApiCompat as Pipeline Task
To add _ApiCompat_ to the build process, an Azure Pipeline task can be created with the embedded _ApiCompat_ executable and its dependencies and, configure the task with the NuGet Package Name and its version as parameters. With this parameters, the task will obtain the package and compare it to the actual build.

These would be the configurable fields for the task:
 - **Display Name**: Default input field for any pipeline task, identifies the task in the task list
 - **NuGet Package Name**: Name of the Package that the task will download to compare.
 - **Version of the NuGet Package**: Version of the Package that the task will download.
 - **Fails on Issues:** If checked, the task will be marked as failed making the build to fail.

### Workflow
Following https://semver.org/ definition, when an incompatible API change is made the MAJOR version number must be incremented.

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

![image](https://user-images.githubusercontent.com/805847/54793116-2e2d2e00-4bfe-11e9-86ec-5880dcf89573.png)

### ApiCompat Tool Validation 
To test the _ApiCompat_  tool, we created a minimal Azure Pipelin Job to:
1. Use dotnet build to compile the _BotBuilder_ project 
2. Use the _NuGet_ task to download a specific version of the _BotBuilder_
3. Run the _ApiCompat_ task to compare APIs configuring:
    - Contracts folder: the _NuGet_ download directory
    - Contract filename: Microsoft.Bot.Builder.dll
    - Implementation folder: the output directory of dotnet build

We made several tests using different binaries versions of _Microsoft.Bot.Builder_. The job looks like the following screenshot:
 
![imagen](https://user-images.githubusercontent.com/22912283/54764559-cf07f300-4bd6-11e9-8abf-1e7139319f3b.png)

### Latest version against latest version (4.3.2)
 
This first test shouldn't raise any compatibility issue as it is comparing against the same version of the _BotBuilder_ binary.
![imagen](https://user-images.githubusercontent.com/22912283/54777254-b4db0e80-4bf0-11e9-9955-1c48f8d5df12.png)
 

### Latest version against previous minor version (4.2.2)
 
Checking compatibilities between minor version may or may not raise incompatibilities. In this case raised 22 issues.

![imagen](https://user-images.githubusercontent.com/22912283/54777464-1e5b1d00-4bf1-11e9-854f-614f8162728c.png)

### Latest version against previous mayor version (3.20.1)
 
Comparing two mayor versions will most likely raise compatibilities issues.

![imagen](https://user-images.githubusercontent.com/22912283/54777317-d2a87380-4bf0-11e9-816f-3b2b73b647d7.png)

### Warning instead of error
When it is chosen the option to show as warning instead of errors, this is the output
![imagen](https://user-images.githubusercontent.com/22912283/54777243-a7be1f80-4bf0-11e9-947e-7738fcca3433.png)

**Comment by ParadoxARG** [comment]
Under ApiCompat title, second line: "compatibilities issues" -> "compatibility issues". 
Has the source code of the task been published in a PR? If so it would be nice to have the link or to add it when it's done.

**Comment by VictorGrycuk** [comment]
Could it be adapted to the New Feature Issue template?
