### ISSUE TITLE
Increase Microsoft.Bot.Streaming code coverage

### ISSUE THREAD

**Issue by sw-joelmut** [southworks/botbuilder-dotnet#384]
Parent issue: # 5167

## Description
Increase the code coverage for the `Microsoft.Bot.Streaming` library.

## Related Pull Requests
- [[Part 1] Increase Microsoft.Bot.Streaming code coverage](https://github.com/southworks/botbuilder-dotnet/pull/385)
- [[Part 2] Increase Microsoft.Bot.Streaming code coverage](https://github.com/southworks/botbuilder-dotnet/pull/386)

## Current Coverage status
![imagen](https://user-images.githubusercontent.com/62260472/127223468-15e884c2-4708-4888-b0ff-5b9db6ab4400.png)

**Comment by ceciliaavila** [comment]
promoted to MS in # 5838
